repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black

    - repo: https://gitlab.com/pycqa/flake8
      rev: master
      hooks:
          - id: flake8

    - repo: https://github.com/asottile/seed-isort-config
      rev: master
      hooks:
          - id: seed-isort-config

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: master
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: master
      hooks:
          - id: mypy
